<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><EnableDefaultCompileItems>false</EnableDefaultCompileItems><DefineConstants>UNITY_EDITOR</DefineConstants><NoWarn>0169;0414;0649</NoWarn></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Assets/Scripts/**/*.cs" />
    <Compile Include="../../../Assets/Editor/**/*.cs" />
    <Compile Include="../../../Assets/Tests/**/*.cs" />
    <Reference Include="$(UnityReferenceEditor)/Managed/UnityEngine/*.dll" />
    <Reference Include="$(UnityReferenceEditor)/Resources/PackageManager/BuiltInPackages/com.unity.ext.nunit/net472/unity-custom/nunit.framework.dll" />
    <Reference Include="$(UnityReferenceEditor)/Resources/PackageManager/ProjectTemplates/libcache/com.unity.template.urp-blank-17.2.1/ScriptAssemblies/UnityEngine.TestRunner.dll" />
    <Reference Include="$(UnityReferenceEditor)/Resources/PackageManager/ProjectTemplates/libcache/com.unity.template.urp-blank-17.2.1/ScriptAssemblies/UnityEditor.TestRunner.dll" />
  </ItemGroup>
</Project>
